# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-12 07:04
from __future__ import unicode_literals

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, help_text='Use *emphasised* or **strong** text, link to <:Another page> or include <:image:An image.jpeg>.'),
        ),
    ]
